config/routes.rb
Ueberslate::Application.routes.draw do

  resources :chat_messages

  resources :chats do
    member do
      post '/', :action => 'post_message'
    end
  end

  resources :role_white_lists

  resources :functions

  resources :roles

  resources :module_packs do
    collection do
      post 'import_module'
    end
  end

  resources :exports

  resources :storages

  resources :translations do
    collection do
      post 'import'
    end
  end

  resources :sources

  resources :messages

  resources :languages

  resources :packs do
    member do
      get 'translate'
      post 'post_translation'
      post 'export'
      post 'grind'
    end
  end

  resources :projects do
    resources :packs
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end
  
  resources  :users


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'
  
  mount Resque::Server, :at => "/resque"
  
  match '*a', :to => 'errors#routing'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/role_white_list.rb
class RoleWhiteList < ActiveRecord::Base
  attr_accessible :action, :controller, :role_id, :any_language
  
  validates_presence_of :role_id, :action, :controller
  validates_uniqueness_of :role_id, :scope => [:action, :controller]
  
end

app/controllers/role_white_lists_controller.rb
class RoleWhiteListsController < ApplicationController
  # GET /role_white_lists
  # GET /role_white_lists.json
  def index
    @role_white_lists = RoleWhiteList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @role_white_lists }
    end
  end

  # GET /role_white_lists/1
  # GET /role_white_lists/1.json
  def show
    @role_white_list = RoleWhiteList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role_white_list }
    end
  end

  # GET /role_white_lists/new
  # GET /role_white_lists/new.json
  def new
    @role_white_list = RoleWhiteList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role_white_list }
    end
  end

  # GET /role_white_lists/1/edit
  def edit
    @role_white_list = RoleWhiteList.find(params[:id])
  end

  # POST /role_white_lists
  # POST /role_white_lists.json
  def create
    @role_white_list = RoleWhiteList.new(params[:role_white_list])
    
    puts @role_white_list.inspect

    respond_to do |format|
      if @role_white_list.save
        format.html { redirect_to params[:redirect], notice: 'Role white list was successfully created.' }
        format.json { render json: @role_white_list, status: :created, location: @role_white_list }
      else
        format.html { render action: "new" }
        format.json { render json: @role_white_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /role_white_lists/1
  # PUT /role_white_lists/1.json
  def update
    @role_white_list = RoleWhiteList.find(params[:id])

    respond_to do |format|
      if @role_white_list.update_attributes(params[:role_white_list])
        format.html { redirect_to @role_white_list, notice: 'Role white list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role_white_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_white_lists/1
  # DELETE /role_white_lists/1.json
  def destroy
    @role_white_list = RoleWhiteList.find(params[:id])
    @role_white_list.destroy

    respond_to do |format|
      format.html { redirect_to params[:redirect] or role_white_lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/role_white_lists_helper.rb
module RoleWhiteListsHelper
end

app/views/role_white_lists/_form.html.erb
<%= form_for(@role_white_list) do |f| %>
  <% if @role_white_list.errors.any? %>
    <div id="error_explanation">
      <h2>Oops</h2>

      <ul>
      <% @role_white_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role_id %><br />
    <%= f.number_field :role_id %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/role_white_lists/edit.html.erb
<h1>Editing role_white_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @role_white_list %> |
<%= link_to 'Back', role_white_lists_path %>

app/views/role_white_lists/index.html.erb
<h1>Listing role_white_lists</h1>

<% @role_white_lists.each do |role_white_list| %>
  <%= row role_white_list, :fields => [:id, :controller, :action, :any_language]%>
<% end %>

<br />

<%= link_to 'New Role white list', new_role_white_list_path %>

app/views/role_white_lists/new.html.erb
<h1>New role_white_list</h1>

<%= render 'form' %>

<%= link_to 'Back', role_white_lists_path %>

app/views/role_white_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Role:</b>
  <%= @role_white_list.role_id %>
</p>

<p>
  <b>Action:</b>
  <%= @role_white_list.action %>
</p>


<%= link_to 'Edit', edit_role_white_list_path(@role_white_list) %> |
<%= link_to 'Back', role_white_lists_path %>