config/routes.rb
Ueberslate::Application.routes.draw do

  resources :chat_messages

  resources :chats do
    member do
      post '/', :action => 'post_message'
    end
  end

  resources :role_white_lists

  resources :functions

  resources :roles

  resources :module_packs do
    collection do
      post 'import_module'
    end
  end

  resources :exports

  resources :storages

  resources :translations do
    collection do
      post 'import'
    end
  end

  resources :sources

  resources :messages

  resources :languages

  resources :packs do
    member do
      get 'translate'
      post 'post_translation'
      post 'export'
      post 'grind'
    end
  end

  resources :projects do
    resources :packs
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end
  
  resources  :users


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'
  
  mount Resque::Server, :at => "/resque"
  
  match '*a', :to => 'errors#routing'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/function.rb
class Function < ActiveRecord::Base
  attr_accessible :role_id, :user_id, :language_id
  
  belongs_to :user
  belongs_to :role
  
  belongs_to :language
  
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  # GET /functions
  # GET /functions.json
  def index
    @functions = Function.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @functions }
    end
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
    @function = Function.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @function }
    end
  end

  # GET /functions/new
  # GET /functions/new.json
  def new
    @function = Function.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @function }
    end
  end

  # GET /functions/1/edit
  def edit
    @function = Function.find(params[:id])
  end

  # POST /functions
  # POST /functions.json
  def create
    @function = Function.new
    @function.user_id = User.find_by_email(params[:email]).id
    @function.language_id = params[:language_id]
    @function.role_id = params[:role_id]

    respond_to do |format|
      if @function.save
        format.html { redirect_to((params[:redirect] or @function), notice: 'Function was successfully created.') }
        format.json { render json: @function, status: :created, location: @function }
      else
        format.html { render action: "new" }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /functions/1
  # PUT /functions/1.json
  def update
    @function = Function.find(params[:id])

    respond_to do |format|
      if @function.update_attributes(params[:function])
        format.html { redirect_to @function, notice: 'Function was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    @function = Function.find(params[:id])
    @function.destroy

    respond_to do |format|
      format.html { redirect_to params[:redirect] or functions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/functions/_form.html.erb
<%= form_for(@function) do |f| %>
  <% if @function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@function.errors.count, "error") %> prohibited this function from being saved:</h2>

      <ul>
      <% @function.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br />
    <%= f.number_field :role_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/functions/edit.html.erb
<h1>Editing function</h1>

<%= render 'form' %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', functions_path %>

app/views/functions/index.html.erb
<h1>Listing functions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @functions.each do |function| %>
  <tr>
    <td><%= function.user_id %></td>
    <td><%= function.role_id %></td>
    <td><%= link_to 'Show', function %></td>
    <td><%= link_to 'Edit', edit_function_path(function) %></td>
    <td><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Function', new_function_path %>

app/views/functions/new.html.erb
<h1>New function</h1>

<%= render 'form' %>

<%= link_to 'Back', functions_path %>

app/views/functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @function.user_id %>
</p>

<p>
  <b>Role:</b>
  <%= @function.role_id %>
</p>


<%= link_to 'Edit', edit_function_path(@function) %> |
<%= link_to 'Back', functions_path %>