config/routes.rb
Ueberslate::Application.routes.draw do

  resources :chat_messages

  resources :chats do
    member do
      post '/', :action => 'post_message'
    end
  end

  resources :role_white_lists

  resources :functions

  resources :roles

  resources :module_packs do
    collection do
      post 'import_module'
    end
  end

  resources :exports

  resources :storages

  resources :translations do
    collection do
      post 'import'
    end
  end

  resources :sources

  resources :messages

  resources :languages

  resources :packs do
    member do
      get 'translate'
      post 'post_translation'
      post 'export'
      post 'grind'
    end
  end

  resources :projects do
    resources :packs
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end
  
  resources  :users


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'
  
  mount Resque::Server, :at => "/resque"
  
  match '*a', :to => 'errors#routing'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  attr_accessible :language_id, :key, :reviewer_id, :string, :user_id, :source_id, :previous_translation_id
  
  belongs_to :source
  belongs_to :language
  belongs_to :user
  belongs_to :reviewer, :foreign_key => :reviewer_id, :primary_key => :user_id
  belongs_to :message, :foreign_key => :key, :primary_key => :key
  
  validates_presence_of :key, :user_id, :source_id, :string
  
  
  def better_than pack_id, translation
    return self.updated_at > translation.updated_at
  end
  
end

app/controllers/translations_controller.rb
require 'adapters/translations_adapter.rb'
require 'jobs/translations_import_job.rb'

class TranslationsController < ApplicationController
  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.page(params[:page])
    @sources = Source.all.map{|source| source.name}
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @translations }
    end
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
    @translation = Translation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @translation }
    end
  end

  # GET /translations/new
  # GET /translations/new.json
  def new
    @translation = Translation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @translation }
    end
  end

  # GET /translations/1/edit
  def edit
    @translation = Translation.find(params[:id])
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(params[:translation])

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation, notice: 'Translation was successfully created.' }
        format.json { render json: @translation, status: :created, location: @translation }
      else
        format.html { render action: "new" }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    if upload = params[:language_archive]
      if source_name = params[:source_name] and !source_name.strip.empty?
        source = Source.find_or_create_by_name(source_name)
        translations = TranslationsAdapter.adapt_archive upload.tempfile
        flash[:notice] = "Queued translations import!"
        res = Resque.enqueue TranslationsImportJob, current_user.id, source.id, translations
      else
        flash[:error] = "Must specify a source!"
      end
    else
        flash[:error] = "Must specify a file!"
    end
    redirect_to translations_path
  end

  # PUT /translations/1
  # PUT /translations/1.json
  def update
    @translation = Translation.find(params[:id])

    respond_to do |format|
      if @translation.update_attributes(params[:translation])
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy

    respond_to do |format|
      format.html { redirect_to translations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= form_for(@translation) do |f| %>
  <% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <%= f.number_field :language_id %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_area :string %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :reviewer_id %><br />
    <%= f.number_field :reviewer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing translation</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<h1>Translations</h1>

<p class="about">
Here you can import a translation pack (.gzip file) or directly use a PrestaShop archive.
<br/>
<strong>Note: </strong>you can upload any file, but only the translations of languages you are authorized to contribute to will be added.
</p>

<%= form_tag import_translations_path, :multipart => true do %>
	<p>
		<%= label_tag :language_archive, "Translation pack" %>
		<%= file_field_tag :language_archive%>
	</p>
	<p>
		<%= label_tag :source_name %>
		<%= text_field_tag :source_name %>
	</p>
	<p>
		<%= submit_tag "upload!"%>
	</p>
<% end %>

<%= javascript_tag do %>
$("#source_name").autocomplete({source: <%= @sources.to_json.html_safe %>})
<% end %>

<%= list @translations, :fields => [:language, :string] %>

<%= link_to 'New Translation', new_translation_path %>

app/views/translations/new.html.erb
<h1>New translation</h1>

<%= render 'form' %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @translation.key %>
</p>

<p>
  <b>Source language:</b>
  <%= @translation.source_language_id %>
</p>

<p>
  <b>Dest language:</b>
  <%= @translation.dest_language_id %>
</p>

<p>
  <b>String:</b>
  <%= @translation.string %>
</p>

<p>
  <b>User:</b>
  <%= @translation.user_id %>
</p>

<p>
  <b>Reviewer:</b>
  <%= @translation.reviewer_id %>
</p>


<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>