config/routes.rb
Ueberslate::Application.routes.draw do

  resources :chat_messages

  resources :chats do
    member do
      post '/', :action => 'post_message'
    end
  end

  resources :role_white_lists

  resources :functions

  resources :roles

  resources :module_packs do
    collection do
      post 'import_module'
    end
  end

  resources :exports

  resources :storages

  resources :translations do
    collection do
      post 'import'
    end
  end

  resources :sources

  resources :messages

  resources :languages

  resources :packs do
    member do
      get 'translate'
      post 'post_translation'
      post 'export'
      post 'grind'
    end
  end

  resources :projects do
    resources :packs
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end
  
  resources  :users


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'
  
  mount Resque::Server, :at => "/resque"
  
  match '*a', :to => 'errors#routing'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/module_pack.rb
class ModulePack < ActiveRecord::Base
  attr_accessible :module_name, :pack_id, :project_id
  
  belongs_to :project
  belongs_to :pack
  
end

app/controllers/module_packs_controller.rb
require 'fileutils'
require 'jobs/import_module_job.rb'

class ModulePacksController < ApplicationController
  # GET /module_packs
  # GET /module_packs.json
  def index
    @module_packs = ModulePack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @module_packs }
    end
  end

  # GET /module_packs/1
  # GET /module_packs/1.json
  def show
    @module_pack = ModulePack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @module_pack }
    end
  end

  # GET /module_packs/new
  # GET /module_packs/new.json
  def new
    @module_pack = ModulePack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @module_pack }
    end
  end

  # GET /module_packs/1/edit
  def edit
    @module_pack = ModulePack.find(params[:id])
  end

  # POST /module_packs
  # POST /module_packs.json
  def create
    @module_pack = ModulePack.new(params[:module_pack])

    respond_to do |format|
      if @module_pack.save
        format.html { redirect_to @module_pack, notice: 'Module pack was successfully created.' }
        format.json { render json: @module_pack, status: :created, location: @module_pack }
      else
        format.html { render action: "new" }
        format.json { render json: @module_pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /module_packs/1
  # PUT /module_packs/1.json
  def update
    @module_pack = ModulePack.find(params[:id])

    respond_to do |format|
      if @module_pack.update_attributes(params[:module_pack])
        format.html { redirect_to @module_pack, notice: 'Module pack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @module_pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /module_packs/1
  # DELETE /module_packs/1.json
  def destroy
    @module_pack = ModulePack.find(params[:id])
    @module_pack.destroy

    respond_to do |format|
      format.html { redirect_to module_packs_url }
      format.json { head :no_content }
    end
  end
  
  def import_module
    
    if ma = params[:module_archive]
      FileUtils.mv ma.tempfile.path, (path="upload/modules/#{ma.original_filename}")
      flash[:notice] = "Processing! Just wait man!"
      Resque.enqueue ImportModuleJob, current_user.id, path
    else
      flash[:notice] = "No module selected!"
    end
    
    redirect_to module_packs_path
  end
  
end

app/helpers/module_packs_helper.rb
module ModulePacksHelper
end

app/views/module_packs/_form.html.erb
<%= form_for(@module_pack) do |f| %>
  <% if @module_pack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@module_pack.errors.count, "error") %> prohibited this module_pack from being saved:</h2>

      <ul>
      <% @module_pack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :module_name %><br />
    <%= f.text_field :module_name %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :pack_id %><br />
    <%= f.text_field :pack_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/module_packs/edit.html.erb
<h1>Editing module_pack</h1>

<%= render 'form' %>

<%= link_to 'Show', @module_pack %> |
<%= link_to 'Back', module_packs_path %>

app/views/module_packs/index.html.erb
<h1>Listing module_packs</h1>

<%= form_tag import_module_module_packs_path, :multipart => true do %>
<%= label_tag :module_archive %>
<%= file_field_tag :module_archive %>
<%= submit_tag "Import!"%>
<% end %>

<br/>

<table>
  <tr>
    <th>Module name</th>
    <th>Project</th>
    <th>Pack</th>
    <th>Archive Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @module_packs.each do |module_pack| %>
  <tr>
    <td><%= module_pack.module_name %></td>
    <td><%= module_pack.project.name %></td>
    <td><%= module_pack.pack.name %></td>
    <td><%= module_pack.archive_path %></td>
    <td><%= link_to 'Show', module_pack %></td>
    <td><%= link_to 'Edit', edit_module_pack_path(module_pack) %></td>
    <td><%= link_to 'Destroy', module_pack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Module pack', new_module_pack_path %>

app/views/module_packs/new.html.erb
<h1>New module_pack</h1>

<%= render 'form' %>

<%= link_to 'Back', module_packs_path %>

app/views/module_packs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Module name:</b>
  <%= @module_pack.module_name %>
</p>

<p>
  <b>Project:</b>
  <%= @module_pack.project_id %>
</p>

<p>
  <b>Pack:</b>
  <%= @module_pack.pack_id %>
</p>


<%= link_to 'Edit', edit_module_pack_path(@module_pack) %> |
<%= link_to 'Back', module_packs_path %>